name: cicd
on:
  push:
    branches:
      - main

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        -
          name: Checkout files
          uses: actions/checkout@v2
  
        -
          name: Install doctl
          uses: digitalocean/action-doctl@v2
          with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        -
          name: Login to DigitalOcean Container Registry
          run: doctl registry login
        - 
          name: Build Docker image 
          run: docker build -t registry.digitalocean.com/devopsapi/api:latest .
        -
          name: Push Docker image to DigitalOcean
          run: docker push registry.digitalocean.com/devops-api/api:latest
    
